import { create } from "zustand";
import { Track, ZoomKeyframe, SilenceBlock, ProjectManifest, OpenedProject, WaveformPage, PlaybackStatus, studioTrackType, ZoomGeneration, ZoomSuggestion, ProjectZoom } from "../lib/types";
import { useSettingsStore } from "./settingsStore";

const RECENT_PROJECTS_KEY = "aeroshoot.recentProjects";
const MAX_RECENT_PROJECTS = 8;

function loadStoredRecentProjects(): string[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(RECENT_PROJECTS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
    }
  } catch {
    // ignore parse error
  }
  return [];
}

function saveStoredRecentProjects(projects: string[]) {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.setItem(RECENT_PROJECTS_KEY, JSON.stringify(projects));
  } catch {
    // ignore save error
  }
}

function barsFromSuggestion(suggestion: ZoomSuggestion, pending: boolean, source?: ProjectZoom["source"]): ZoomKeyframe[] {
  const ranges = suggestion.editedRanges.filter((range) => range.endUs > range.startUs);
  const fallback = [{ startUs: suggestion.sourceStartUs, endUs: suggestion.sourceEndUs }];
  const used = ranges.length > 0 ? ranges : fallback;
  return used.map((range, index) => ({
    id: used.length === 1 ? suggestion.id : `${suggestion.id}-${index}`,
    zoomId: suggestion.id,
    tUs: range.startUs,
    endUs: range.endUs,
    sourceStartUs: suggestion.sourceStartUs,
    sourceEndUs: suggestion.sourceEndUs,
    normX: suggestion.centerX,
    normY: suggestion.centerY,
    scale: suggestion.scale,
    durationMs: Math.round((range.endUs - range.startUs) / 1000),
    transitionMs: Math.round(suggestion.transitionUs / 1000),
    origin: suggestion.origin,
    contributingEventSeqs: suggestion.contributingEventSeqs,
    source,
    pending,
    isAutoGenerated: pending || source === "generated",
  }));
}

function mergeZoomBars(persisted: ProjectZoom[] | undefined, pending: ZoomSuggestion[]): ZoomKeyframe[] {
  const persistedBars = (persisted ?? []).flatMap((zoom) =>
    barsFromSuggestion(
      {
        id: zoom.id,
        sourceStartUs: zoom.sourceStartUs,
        sourceEndUs: zoom.sourceEndUs,
        centerX: zoom.centerX,
        centerY: zoom.centerY,
        scale: zoom.scale,
        transitionUs: zoom.transitionUs,
        origin: zoom.origin,
        contributingEventSeqs: zoom.contributingEventSeqs ?? [],
        editedRanges: zoom.editedRanges ?? [],
      },
      false,
      zoom.source,
    ),
  );
  const pendingBars = pending.flatMap((suggestion) => barsFromSuggestion(suggestion, true));
  return [...persistedBars, ...pendingBars].sort((a, b) => a.tUs - b.tUs || a.id.localeCompare(b.id));
}

interface ProjectStore {
  openedProject: OpenedProject | null;
  projectPath: string | null;
  recentProjects: string[];
  playbackGeneration: number;
  playbackError: string | null;
  previewAvailable: boolean;
  applyPlaybackStatus: (status: PlaybackStatus) => void;
  loadOpenedProject: (project: OpenedProject, projectPath?: string) => void;
  clearProject: () => void;
  manifest: ProjectManifest | null;
  tracks: Track[];
  zoomKeyframes: ZoomKeyframe[];
  pendingZoomSuggestions: ZoomSuggestion[];
  zoomDiagnostics: string[];
  currentTimeUs: number;
  durationUs: number;
  isPlaying: boolean;
  activeSilenceBlocks: SilenceBlock[];
  silenceAnalysis: { projectHandle: string; revision: number } | null;
  isSilenceModalOpen: boolean;

  // Actions
  setProjectPath: (path: string | null) => void;
  addRecentProject: (path: string) => void;
  removeRecentProject: (path: string) => void;
  clearRecentProjects: () => void;
  setManifest: (manifest: ProjectManifest | null) => void;
  setCurrentTimeUs: (timeUs: number) => void;
  setIsPlaying: (isPlaying: boolean) => void;
  togglePlayPause: () => void;
  applyZoomGeneration: (generation: Pick<ZoomGeneration, "suggestions" | "diagnostics">) => void;
  setSilenceBlocks: (
    blocks: SilenceBlock[],
    analysis?: { projectHandle: string; revision: number } | null,
  ) => void;
  toggleSilenceBlock: (id: string) => void;
  applySilenceCuts: () => void;
  setIsSilenceModalOpen: (open: boolean) => void;
  setTrackWaveform: (trackId: string, waveform: WaveformPage) => void;
  applyOpenedProject: (project: OpenedProject) => void;
}

export const useProjectStore = create<ProjectStore>((set, get) => ({
  openedProject: null,
  projectPath: null,
  recentProjects: loadStoredRecentProjects(),
  playbackGeneration: 0,
  playbackError: null,
  previewAvailable: false,
  setProjectPath: (path) => set({ projectPath: path }),
  addRecentProject: (path) => {
    const clean = path.trim();
    if (!clean) return;
    const current = get().recentProjects.filter((p) => p !== clean);
    const updated = [clean, ...current].slice(0, MAX_RECENT_PROJECTS);
    saveStoredRecentProjects(updated);
    set({ recentProjects: updated });
  },
  removeRecentProject: (path) => {
    const updated = get().recentProjects.filter((p) => p !== path);
    saveStoredRecentProjects(updated);
    set({ recentProjects: updated });
  },
  clearRecentProjects: () => {
    saveStoredRecentProjects([]);
    set({ recentProjects: [] });
  },
  applyPlaybackStatus: (status) => set((state) => {
    if (state.openedProject?.projectHandle !== status.projectHandle || status.generation < state.playbackGeneration) return state;
    return { currentTimeUs: Math.min(status.positionUs, state.durationUs), isPlaying: status.state === "playing", playbackGeneration: status.generation, playbackError: status.error, previewAvailable: status.previewAvailable };
  }),
  loadOpenedProject: (project, projectPath) => {
    const resolvedPath = projectPath ?? project.projectPath ?? get().projectPath ?? undefined;
    if (resolvedPath) {
      get().addRecentProject(resolvedPath);
    }
    if (project.layout) {
      useSettingsStore.getState().hydrateLayout(project.layout);
    }
    set({
      openedProject: project,
      projectPath: resolvedPath ?? null,
      playbackGeneration: 0, playbackError: null, previewAvailable: false,
      manifest: project.manifest,
      durationUs: project.editedDurationUs,
      currentTimeUs: 0,
      isPlaying: false,
      pendingZoomSuggestions: [],
      zoomKeyframes: mergeZoomBars(project.zooms, []),
      zoomDiagnostics: [],
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
      tracks: project.tracks.map(({ descriptor, segmentCount, availableSegmentCount }) => ({
        id: descriptor.id,
        trackType: studioTrackType(descriptor.trackType),
        name: `${descriptor.id} · ${availableSegmentCount}/${segmentCount} segments available`,
        muted: false,
        volume: 1,
        intervals: [],
      })),
    });
  },
  clearProject: () => {
    useSettingsStore.setState({ layoutOwnedByProject: false });
    set({
      openedProject: null,
      projectPath: null,
      playbackError: null,
      previewAvailable: false,
      manifest: null,
      tracks: [],
      durationUs: 0,
      currentTimeUs: 0,
      isPlaying: false,
      zoomKeyframes: [],
      pendingZoomSuggestions: [],
      zoomDiagnostics: [],
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
    });
  },
  manifest: null,
  tracks: [],
  zoomKeyframes: [],
  pendingZoomSuggestions: [],
  zoomDiagnostics: [],
  currentTimeUs: 0,
  durationUs: 0,
  isPlaying: false,
  activeSilenceBlocks: [],
  silenceAnalysis: null,
  isSilenceModalOpen: false,

  setManifest: (manifest) =>
    set({
      manifest,
      durationUs: manifest ? manifest.durationUs : 0,
    }),

  setCurrentTimeUs: (timeUs) => {
    const { durationUs } = get();
    const clamped = Math.max(0, Math.min(timeUs, durationUs));
    set({ currentTimeUs: clamped });
  },

  setIsPlaying: (isPlaying) => set({ isPlaying }),

  togglePlayPause: () => set((state) => ({ isPlaying: !state.isPlaying })),

  applyZoomGeneration: (generation) =>
    set((state) => ({
      zoomDiagnostics: generation.diagnostics,
      pendingZoomSuggestions: generation.suggestions,
      zoomKeyframes: mergeZoomBars(state.openedProject?.zooms, generation.suggestions),
    })),

  setSilenceBlocks: (blocks, analysis = null) =>
    set({
      activeSilenceBlocks: blocks,
      silenceAnalysis: blocks.length === 0 ? null : analysis,
    }),

  toggleSilenceBlock: (id) =>
    set((state) => ({
      activeSilenceBlocks: state.activeSilenceBlocks.map((b) =>
        b.id === id ? { ...b, selected: !b.selected } : b
      ),
    })),

  applySilenceCuts: () => {
    const { activeSilenceBlocks } = get();
    const selectedBlocks = activeSilenceBlocks.filter((b) => b.selected);
    if (selectedBlocks.length === 0) return;
    set({
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
    });
  },

  setIsSilenceModalOpen: (open) => set({ isSilenceModalOpen: open }),

  setTrackWaveform: (trackId, waveform) =>
    set((state) => ({
      tracks: state.tracks.map((track) =>
        track.id === trackId ? { ...track, waveform } : track
      ),
    })),

  applyOpenedProject: (project) =>
    set((state) => {
      if (state.openedProject?.projectHandle !== project.projectHandle) return state;
      const taken = new Set([
        ...(project.zooms ?? []).map((zoom) => zoom.id),
        ...(project.dismissedZoomIds ?? []),
      ]);
      const pending = state.pendingZoomSuggestions.filter((suggestion) => !taken.has(suggestion.id));
      if (project.layout) {
        useSettingsStore.getState().hydrateLayout(project.layout);
      }
      const silenceStale =
        !state.silenceAnalysis ||
        state.silenceAnalysis.projectHandle !== project.projectHandle ||
        state.silenceAnalysis.revision !== project.revision;
      return {
        openedProject: project,
        manifest: project.manifest,
        durationUs: project.editedDurationUs,
        currentTimeUs: Math.min(state.currentTimeUs, project.editedDurationUs),
        pendingZoomSuggestions: pending,
        zoomKeyframes: mergeZoomBars(project.zooms, pending),
        activeSilenceBlocks: silenceStale ? [] : state.activeSilenceBlocks,
        silenceAnalysis: silenceStale ? null : state.silenceAnalysis,
        tracks: project.tracks.map(({ descriptor, segmentCount, availableSegmentCount }) => {
          const existing = state.tracks.find((track) => track.id === descriptor.id);
          return {
            id: descriptor.id,
            trackType: studioTrackType(descriptor.trackType),
            name: `${descriptor.id} · ${availableSegmentCount}/${segmentCount} segments available`,
            muted: existing?.muted ?? false,
            volume: existing?.volume ?? 1,
            intervals: existing?.intervals ?? [],
            waveform: existing?.waveform,
          };
        }),
      };
    }),
}));
