import { api } from "../lib/ipc";
import { create } from "zustand";
import { ZoomKeyframe, SilenceBlock, OpenedProject, WaveformBucket, PlaybackStatus, ZoomGeneration, ZoomSuggestion, ProjectZoom } from "../lib/types";
import { broadcastProject, broadcastCaptionsChanged } from "../lib/windowSync";
import { useSettingsStore } from "./settingsStore";

const RECENT_PROJECTS_KEY = "aeroedits.recentProjects";
const MAX_RECENT_PROJECTS = 8;

function loadStoredRecentProjects(): string[] {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(RECENT_PROJECTS_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
    }
  } catch {
    // ignore parse error
  }
  return [];
}

function saveStoredRecentProjects(projects: string[]) {
  if (typeof localStorage === "undefined") return;
  try {
    localStorage.setItem(RECENT_PROJECTS_KEY, JSON.stringify(projects));
  } catch {
    // ignore save error
  }
}

function barsFromSuggestion(suggestion: ZoomSuggestion, pending: boolean, source?: ProjectZoom["source"]): ZoomKeyframe[] {
  // The backend places every zoom; none left (its footage was cut) means no bar at all.
  const used = (suggestion.editedRanges ?? []).filter((range) => range.endUs > range.startUs);
  return used.map((range, index) => ({
    id: used.length === 1 ? suggestion.id : `${suggestion.id}-${index}`,
    zoomId: suggestion.id,
    tUs: range.startUs,
    endUs: range.endUs,
    sourceStartUs: suggestion.sourceStartUs,
    sourceEndUs: suggestion.sourceEndUs,
    normX: suggestion.centerX,
    normY: suggestion.centerY,
    scale: suggestion.scale,
    durationMs: Math.round((range.endUs - range.startUs) / 1000),
    transitionMs: Math.round(suggestion.transitionUs / 1000),
    origin: suggestion.origin,
    contributingEventSeqs: suggestion.contributingEventSeqs,
    source,
    pending,
    isAutoGenerated: pending || source === "generated",
  }));
}

function mergeZoomBars(persisted: ProjectZoom[] | undefined, pending: ZoomSuggestion[]): ZoomKeyframe[] {
  const persistedBars = (persisted ?? []).flatMap((zoom) =>
    barsFromSuggestion(
      {
        id: zoom.id,
        sourceStartUs: zoom.sourceStartUs,
        sourceEndUs: zoom.sourceEndUs,
        centerX: zoom.centerX,
        centerY: zoom.centerY,
        scale: zoom.scale,
        transitionUs: zoom.transitionUs,
        origin: zoom.origin,
        contributingEventSeqs: zoom.contributingEventSeqs ?? [],
        editedRanges: zoom.editedRanges ?? [],
      },
      false,
      zoom.source,
    ),
  );
  const pendingBars = pending.flatMap((suggestion) => barsFromSuggestion(suggestion, true));
  return [...persistedBars, ...pendingBars].sort((a, b) => a.tUs - b.tUs || a.id.localeCompare(b.id));
}

interface ProjectStore {
  openedProject: OpenedProject | null;
  projectPath: string | null;
  recentProjects: string[];
  playbackGeneration: number;
  playbackError: string | null;
  previewAvailable: boolean;
  applyPlaybackStatus: (status: PlaybackStatus) => void;
  loadOpenedProject: (project: OpenedProject, projectPath?: string) => void;
  clearProject: () => void;
  /** Waveforms by sound (`<asset>.<stream>`), over its own time. */
  waveforms: Record<string, WaveformBucket[]>;
  setWaveform: (key: string, buckets: WaveformBucket[]) => void;
  zoomKeyframes: ZoomKeyframe[];
  pendingZoomSuggestions: ZoomSuggestion[];
  zoomDiagnostics: string[];
  /** The zoom picked on the timeline lane or in the Zoom panel. */
  selectedZoomId?: string;
  /** The clips selected on the timeline (linked partners included); the Inspector shows the first. */
  selectedClipIds: string[];
  /** The short this window shows as its timeline (the Shorts Studio), if any. */
  viewShort?: string;
  setViewShort: (shortId: string | undefined) => void;
  /** The short playing instead of the video (set by the Shorts Studio). */
  playbackShortId?: string;
  /** Bumped whenever a transcript changes, so captions and the transcript panel reload. */
  captionsVersion: number;
  /** Marks transcripts changed here (and tells the other windows) or in another window. */
  bumpCaptions: (fromOtherWindow?: boolean) => void;
  /** The timeline's selection, shared so other panels can act on it. */
  timelineSelection: { startUs: number; endUs: number } | null;
  currentTimeUs: number;
  durationUs: number;
  isPlaying: boolean;
  activeSilenceBlocks: SilenceBlock[];
  silenceAnalysis: { projectHandle: string; revision: number } | null;
  isSilenceModalOpen: boolean;

  // Actions
  setProjectPath: (path: string | null) => void;
  addRecentProject: (path: string) => void;
  removeRecentProject: (path: string) => void;
  clearRecentProjects: () => void;
  setCurrentTimeUs: (timeUs: number) => void;
  setIsPlaying: (isPlaying: boolean) => void;
  togglePlayPause: () => void;
  applyZoomGeneration: (generation: Pick<ZoomGeneration, "suggestions" | "diagnostics">) => void;
  setSelectedZoomId: (id?: string) => void;
  setSelectedClipIds: (ids: string[]) => void;
  setTimelineSelection: (selection: { startUs: number; endUs: number } | null) => void;
  setSilenceBlocks: (
    blocks: SilenceBlock[],
    analysis?: { projectHandle: string; revision: number } | null,
  ) => void;
  toggleSilenceBlock: (id: string) => void;
  applySilenceCuts: () => void;
  setIsSilenceModalOpen: (open: boolean) => void;
  /** Applies an edit's result. `remote` marks one broadcast by another window: it is applied
   *  only if newer, and not broadcast again. */
  applyOpenedProject: (project: OpenedProject, options?: { remote?: boolean }) => void;
}

export const useProjectStore = create<ProjectStore>((set, get) => ({
  openedProject: null,
  projectPath: null,
  recentProjects: loadStoredRecentProjects(),
  playbackGeneration: 0,
  playbackError: null,
  previewAvailable: false,
  setProjectPath: (path) => set({ projectPath: path }),
  addRecentProject: (path) => {
    const clean = path.trim();
    if (!clean) return;
    const current = get().recentProjects.filter((p) => p !== clean);
    const updated = [clean, ...current].slice(0, MAX_RECENT_PROJECTS);
    saveStoredRecentProjects(updated);
    set({ recentProjects: updated });
  },
  removeRecentProject: (path) => {
    const updated = get().recentProjects.filter((p) => p !== path);
    saveStoredRecentProjects(updated);
    set({ recentProjects: updated });
  },
  clearRecentProjects: () => {
    saveStoredRecentProjects([]);
    set({ recentProjects: [] });
  },
  applyPlaybackStatus: (status) => set((state) => {
    if (state.openedProject?.projectHandle !== status.projectHandle || status.generation < state.playbackGeneration) return state;
    // The engine plays something this window does not show (a short in the editor, or the
    // video in the Shorts Studio): note it, but keep this window's own playhead.
    if ((status.shortId ?? undefined) !== state.viewShort) {
      return { playbackShortId: status.shortId, isPlaying: false, playbackGeneration: status.generation };
    }
    return { currentTimeUs: Math.min(status.positionUs, state.durationUs), isPlaying: status.state === "playing", playbackGeneration: status.generation, playbackError: status.error, previewAvailable: status.previewAvailable, playbackShortId: status.shortId };
  }),
  loadOpenedProject: (project, projectPath) => {
    const resolvedPath = projectPath ?? project.projectPath ?? get().projectPath ?? undefined;
    if (resolvedPath) {
      get().addRecentProject(resolvedPath);
    }
    if (project.layout) {
      useSettingsStore.getState().hydrateLayout(project.layout);
    }
    set({
      openedProject: project,
      projectPath: resolvedPath ?? null,
      playbackGeneration: 0, playbackError: null, previewAvailable: false,
      durationUs: project.durationUs,
      waveforms: {},
      selectedClipIds: [],
      currentTimeUs: 0,
      isPlaying: false,
      pendingZoomSuggestions: [],
      zoomKeyframes: mergeZoomBars(project.zooms, []),
      zoomDiagnostics: [],
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
    });
  },
  clearProject: () => {
    useSettingsStore.setState({ layoutOwnedByProject: false });
    set({
      openedProject: null,
      projectPath: null,
      playbackError: null,
      previewAvailable: false,
      waveforms: {},
      selectedClipIds: [],
      durationUs: 0,
      currentTimeUs: 0,
      isPlaying: false,
      zoomKeyframes: [],
      pendingZoomSuggestions: [],
      zoomDiagnostics: [],
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
    });
  },
  waveforms: {},
  setWaveform: (key, buckets) => set((state) => ({ waveforms: { ...state.waveforms, [key]: buckets } })),
  zoomKeyframes: [],
  pendingZoomSuggestions: [],
  zoomDiagnostics: [],
  selectedZoomId: undefined,
  selectedClipIds: [],
  captionsVersion: 0,
  viewShort: undefined,
  setViewShort: (viewShort) => set({ viewShort }),
  playbackShortId: undefined,
  bumpCaptions: (fromOtherWindow?: boolean) => {
    set((state) => ({ captionsVersion: state.captionsVersion + 1 }));
    if (!fromOtherWindow) broadcastCaptionsChanged();
  },
  timelineSelection: null,
  currentTimeUs: 0,
  durationUs: 0,
  isPlaying: false,
  activeSilenceBlocks: [],
  silenceAnalysis: null,
  isSilenceModalOpen: false,

  setCurrentTimeUs: (timeUs) => {
    const { durationUs } = get();
    const clamped = Math.max(0, Math.min(timeUs, durationUs));
    set({ currentTimeUs: clamped });
  },

  setIsPlaying: (isPlaying) => set({ isPlaying }),

  togglePlayPause: () => set((state) => ({ isPlaying: !state.isPlaying })),

  setSelectedZoomId: (selectedZoomId) => set({ selectedZoomId }),
  setSelectedClipIds: (selectedClipIds) => set({ selectedClipIds }),
  setTimelineSelection: (timelineSelection) => set({ timelineSelection }),

  applyZoomGeneration: (generation) =>
    set((state) => ({
      zoomDiagnostics: generation.diagnostics,
      pendingZoomSuggestions: generation.suggestions,
      zoomKeyframes: mergeZoomBars(state.openedProject?.zooms, generation.suggestions),
    })),

  setSilenceBlocks: (blocks, analysis = null) =>
    set({
      activeSilenceBlocks: blocks,
      silenceAnalysis: blocks.length === 0 ? null : analysis,
    }),

  toggleSilenceBlock: (id) =>
    set((state) => ({
      activeSilenceBlocks: state.activeSilenceBlocks.map((b) =>
        b.id === id ? { ...b, selected: !b.selected } : b
      ),
    })),

  applySilenceCuts: () => {
    const { activeSilenceBlocks } = get();
    const selectedBlocks = activeSilenceBlocks.filter((b) => b.selected);
    if (selectedBlocks.length === 0) return;
    set({
      activeSilenceBlocks: [],
      silenceAnalysis: null,
      isSilenceModalOpen: false,
    });
  },

  setIsSilenceModalOpen: (open) => set({ isSilenceModalOpen: open }),

  applyOpenedProject: (project, options) => {
    const current = get().openedProject;
    // A window showing a short turns every project it is handed into that short's view.
    const viewShort = get().viewShort;
    if (viewShort && project.shortView !== viewShort) {
      void api
        .projectShortView(project.projectHandle, viewShort)
        .then((view) => get().applyOpenedProject(view, options))
        .catch(() => undefined);
      if (!options?.remote) broadcastProject(project);
      return;
    }
    // An older (or the same) revision is stale, unless it is a different view of it (a short's).
    if (options?.remote && current && project.revision <= current.revision && project.projectHandle === current.projectHandle && project.shortView === current.shortView) {
      return;
    }
    if (!options?.remote && current?.projectHandle === project.projectHandle) broadcastProject(project);
    set((state) => {
      if (state.openedProject?.projectHandle !== project.projectHandle) return state;
      const taken = new Set([
        ...(project.zooms ?? []).map((zoom) => zoom.id),
        ...(project.dismissedZoomIds ?? []),
      ]);
      const pending = state.pendingZoomSuggestions.filter((suggestion) => !taken.has(suggestion.id));
      if (project.layout) {
        useSettingsStore.getState().hydrateLayout(project.layout);
      }
      const silenceStale =
        !state.silenceAnalysis ||
        state.silenceAnalysis.projectHandle !== project.projectHandle ||
        state.silenceAnalysis.revision !== project.revision;
      const clipIds = new Set(project.sequence.tracks.flatMap((t) => t.clips.map((c) => c.id)));
      const kept = state.selectedClipIds.filter((id) => clipIds.has(id));
      return {
        openedProject: project,
        durationUs: project.durationUs,
        currentTimeUs: Math.min(state.currentTimeUs, project.durationUs),
        selectedClipIds: kept.length === state.selectedClipIds.length ? state.selectedClipIds : kept,
        pendingZoomSuggestions: pending,
        zoomKeyframes: mergeZoomBars(project.zooms, pending),
        activeSilenceBlocks: silenceStale ? [] : state.activeSilenceBlocks,
        silenceAnalysis: silenceStale ? null : state.silenceAnalysis,
      };
    });
  },
}));
