/** A sound's whole waveform: bars splitting `[0, durationUs)` of its own time evenly. */
export interface WaveformOverview {
  trackId: string;
  durationUs: number;
  /** Each bar's peak and RMS as `round(sqrt(level) * 254)`; 255 where there is no sound. */
  peaks: number[];
  rms: number[];
  diagnostics: string[];
}

export type ZoomOrigin = "click" | "dwell" | "cluster";

export interface EditedRange {
  startUs: number;
  endUs: number;
}

export interface ZoomConfig {
  generationVersion: number;
  dwellRadiusNorm: number;
  minDwellUs: number;
  clusterRadiusNorm: number;
  clusterGapUs: number;
  rapidClickWindowUs: number;
  minHoldUs: number;
  transitionUs: number;
  maxScale: number;
  clickScale: number;
  dwellScale: number;
  geometryUncertaintyUs: number;
  primaryButtons: number[];
  viewportMargin: number;
}

export interface ZoomSuggestion {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
  transitionUs: number;
  origin: ZoomOrigin;
  contributingEventSeqs: number[];
  editedRanges: EditedRange[];
}

export interface ZoomGeneration {
  version: number;
  config: ZoomConfig;
  suggestions: ZoomSuggestion[];
  diagnostics: string[];
}

export type ZoomSource = "generated" | "manual";

export interface ProjectZoom {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
  transitionUs: number;
  origin: ZoomOrigin;
  contributingEventSeqs: number[];
  source: ZoomSource;
  editedRanges: EditedRange[];
  /** The recording whose clock the times are on. */
  media?: string;
  /** Stays on its center instead of following the mouse. */
  fixed?: boolean;
}

/** The project's auto-zoom settings (src-tauri/src/zoom/mod.rs `ZoomSettings`). */
export interface ZoomSettings {
  /** How far a zoom on clicks goes in. */
  clickScale: number;
  /** How far a zoom where the mouse rests goes in; 1 is off. */
  hoverScale: number;
  transitionMs: number;
  /** The shortest zoom. */
  minHoldMs: number;
  /** Activity closer than this is one zoom that follows the mouse. */
  mergeGapMs: number;
  /** The most zooms per recording: the strongest moments are kept. */
  maxZooms: number;
  /** The camera follows the mouse inside a zoom. */
  follow: boolean;
  /** How calmly: the camera's lag behind the mouse. */
  followMs: number;
}

export const DEFAULT_ZOOM_SETTINGS: ZoomSettings = {
  clickScale: 1.8,
  hoverScale: 1.4,
  transitionMs: 700,
  minHoldMs: 1800,
  mergeGapMs: 2500,
  maxZooms: 10,
  follow: true,
  followMs: 700,
};

export interface ManualZoomInput {
  editedStartUs: number;
  editedEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
}

export interface ZoomKeyframe {
  id: string;
  zoomId: string;
  tUs: number;
  endUs: number;
  sourceStartUs: number;
  sourceEndUs: number;
  normX: number;
  normY: number;
  scale: number;
  durationMs: number;
  transitionMs: number;
  origin?: ZoomOrigin;
  contributingEventSeqs?: number[];
  source?: ZoomSource;
  pending: boolean;
  isAutoGenerated?: boolean;
}

export type CameraBubbleShape = "rect" | "circle" | "squircle" | "rect_16_9";
export type CameraBubbleSize = "sm" | "md" | "lg" | "xl";
export type CameraBubblePosition = "top-left" | "top-right" | "bottom-left" | "bottom-right" | "custom";

export interface CameraBubbleSettings {
  enabled: boolean;
  shape: CameraBubbleShape;
  size: CameraBubbleSize;
  sizePct: number; // 5 to 60, percent of the canvas short side
  roundnessPct: number; // 0 to 50, rect corner radius as percent of the bubble short side
  position: CameraBubblePosition;
  customX: number;
  customY: number;
  borderColor: string;
  borderWidth: number;
  mirror: boolean;
  shadow: boolean;
}

export type BackgroundPreset = "aurora" | "sunset" | "ocean" | "forest" | "candy" | "graphite";

export interface ScreenCrop {
  left: number; // 0 to 45, percent of the source
  top: number;
  right: number;
  bottom: number;
}

export interface CanvasSettings {
  backgroundType: "gradient" | "solid" | "wallpaper" | "preset";
  backgroundPreset: BackgroundPreset;
  colorStart: string;
  colorEnd: string;
  screenCrop: ScreenCrop;
  screenScalePct: number; // 40 to 100
  cornerRadiusPx: number; // 0 to 32
  shadowBlurPx: number; // 0 to 40
  shadowOpacity: number; // 0.0 to 1.0
  aspectRatio: "16:9" | "9:16" | "4:3" | "1:1";
  /** Draw the recorded mouse pointer (recordings that left it out of the video). */
  cursorVisible: boolean;
  /** Pointer size, percent of its recorded size: 25 to 400. */
  cursorSizePct: number;
}

/** Audio polish. Each effect has its own switch and applies to playback and export. */
export interface AudioSettings {
  normalize: boolean;
  /** Integrated loudness target in LUFS, -30 to -8. */
  targetLufs: number;
  noiseReduction: boolean;
  /** How far background noise is lowered, 3 to 30 dB. */
  noiseReductionDb: number;
  duckSystemAudio: boolean;
  /** How far system audio is lowered under speech, 3 to 30 dB. */
  duckDb: number;
  /** Volume, noise reduction and ducking per audio track id; absent plays as recorded. */
  tracks?: Record<string, TrackMix>;
}

/** One audio track's mix, kept under the track's id. Muting is the track's own switch. */
export interface TrackMix {
  /** Gain in dB, -30 to +12. */
  volumeDb: number;
  /** Noise reduction in dB (3 to 30); absent follows the project's switch for speech. */
  denoiseDb?: number;
  /** Lowered this many dB under speech (3 to 30); absent follows the project's switch for background sound. */
  duckDb?: number;
}

export const DEFAULT_TRACK_MIX: TrackMix = { volumeDb: 0 };
export const TRACK_VOLUME_DB_RANGE = { min: -30, max: 12 } as const;

export const DEFAULT_AUDIO_SETTINGS: AudioSettings = {
  normalize: false,
  targetLufs: -14,
  noiseReduction: false,
  noiseReductionDb: 12,
  duckSystemAudio: false,
  duckDb: 12,
};

/** Captions burned into playback and export from a track's transcript. */
export interface CaptionSettings {
  enabled: boolean;
  /** The sound to caption (`<asset>.<stream>`); unset picks the first speech on the timeline. */
  trackId?: string;
  position: "bottom" | "middle" | "top";
  /** Distance from the top or bottom edge, 0 to 45 % of the canvas height. */
  offsetPct: number;
  /** Text size, 2 to 15 % of the canvas height. */
  fontSizePct: number;
  textColor: string;
  highlightWords: boolean;
  highlightColor: string;
  outline: boolean;
  background: boolean;
  backgroundColor: string;
  /** 0 to 1. */
  backgroundOpacity: number;
  uppercase: boolean;
  /** Most words on screen at once, 1 to 12. */
  maxWords: number;
  /** Most lines a caption takes (1 to 3). */
  maxLines?: number;
}

export const DEFAULT_CAPTION_SETTINGS: CaptionSettings = {
  enabled: false,
  position: "bottom",
  offsetPct: 8,
  fontSizePct: 5.5,
  textColor: "#FFFFFF",
  highlightWords: true,
  highlightColor: "#FACC15",
  outline: true,
  background: false,
  backgroundColor: "#000000",
  backgroundOpacity: 0.55,
  uppercase: false,
  maxWords: 6,
};

export interface EditLayout {
  aspectRatio: string;
  paddingPx: number;
  backgroundType?: string;
  colorStart?: string;
  colorEnd?: string;
  cornerRadiusPx?: number;
  shadowBlurPx?: number;
  shadowOpacity?: number;
  wallpaperAsset?: string | null;
  backgroundPreset?: string;
  screenCropLeft?: number;
  screenCropTop?: number;
  screenCropRight?: number;
  screenCropBottom?: number;
  screenScalePct?: number;
  webcamEnabled?: boolean;
  webcamShape?: string;
  webcamSize?: string;
  webcamSizePct?: number;
  webcamRoundnessPct?: number;
  webcamPosition?: string;
  webcamCustomX?: number;
  webcamCustomY?: number;
  webcamBorderColor?: string;
  webcamBorderWidth?: number;
  webcamMirror?: boolean;
  webcamShadow?: boolean;
  cursorVisible?: boolean;
  cursorSizePct?: number;
}

export const LAYOUT_UNSUPPORTED = {
  rect169: "16:9 webcam crop stays disabled until a dedicated bubble aspect path ships",
} as const;

/// Built-in backgrounds. Mirrors `preset_recipe` in src-tauri/src/render/mod.rs so the
/// swatches look like what preview and export render.
export const BACKGROUND_PRESETS: {
  key: BackgroundPreset;
  label: string;
  base: string;
  blobs: [x: number, y: number, radius: number, color: string][];
}[] = [
  { key: "aurora", label: "Aurora", base: "#0b1026", blobs: [[0.15, 0.2, 0.7, "#3b82f6"], [0.85, 0.3, 0.6, "#a855f7"], [0.5, 1.0, 0.7, "#14b8a6"]] },
  { key: "sunset", label: "Sunset", base: "#1e1033", blobs: [[0.2, 0.9, 0.8, "#f97316"], [0.8, 0.2, 0.7, "#db2777"], [0.55, 0.55, 0.4, "#facc15"]] },
  { key: "ocean", label: "Ocean", base: "#031b34", blobs: [[0.1, 0.1, 0.8, "#0ea5e9"], [0.9, 0.9, 0.8, "#1d4ed8"], [0.6, 0.4, 0.45, "#22d3ee"]] },
  { key: "forest", label: "Forest", base: "#052e16", blobs: [[0.2, 0.8, 0.8, "#15803d"], [0.85, 0.15, 0.6, "#65a30d"], [0.6, 0.6, 0.45, "#0f766e"]] },
  { key: "candy", label: "Candy", base: "#3b0764", blobs: [[0.1, 0.3, 0.7, "#ec4899"], [0.9, 0.7, 0.7, "#8b5cf6"], [0.5, 0.0, 0.5, "#f472b6"]] },
  { key: "graphite", label: "Graphite", base: "#111113", blobs: [[0.2, 0.15, 0.8, "#3f3f46"], [0.85, 0.85, 0.7, "#27272a"], [0.6, 0.4, 0.4, "#52525b"]] },
];

/// CSS approximation of a built-in background for a 16:9 swatch.
export function presetBackgroundCss(key: BackgroundPreset): string {
  const preset = BACKGROUND_PRESETS.find((p) => p.key === key) ?? BACKGROUND_PRESETS[0];
  const layers = preset.blobs.map(
    ([x, y, r, color]) =>
      `radial-gradient(ellipse ${r * 100}% ${r * 178}% at ${x * 100}% ${y * 100}%, ${color}d9, transparent)`,
  );
  return [...layers, preset.base].join(", ");
}

export const WEBCAM_SIZE_PRESET_PCT: Record<CameraBubbleSize, number> = {
  sm: 12.5,
  md: 20,
  lg: 28,
  xl: 36,
};

export function canvasFromLayout(layout: EditLayout): CanvasSettings {
  const aspect = layout.aspectRatio;
  const preset = BACKGROUND_PRESETS.find((p) => p.key === layout.backgroundPreset);
  return {
    backgroundType:
      layout.backgroundType === "solid" ||
      layout.backgroundType === "wallpaper" ||
      layout.backgroundType === "preset"
        ? layout.backgroundType
        : "gradient",
    backgroundPreset: preset?.key ?? "aurora",
    colorStart: layout.colorStart ?? "#312e81",
    colorEnd: layout.colorEnd ?? "#0f172a",
    screenCrop: {
      left: layout.screenCropLeft ?? 0,
      top: layout.screenCropTop ?? 0,
      right: layout.screenCropRight ?? 0,
      bottom: layout.screenCropBottom ?? 0,
    },
    // Canvas padding is gone: screen scale does the same job. Older projects keep their
    // look by folding the padding into the scale (padding is in 1080p-short-side pixels).
    screenScalePct: Math.max(
      1,
      Math.round(
        (layout.screenScalePct ?? 100) * Math.max(0, (1080 - 2 * (layout.paddingPx ?? 0)) / 1080),
      ),
    ),
    cornerRadiusPx: layout.cornerRadiusPx ?? 0,
    shadowBlurPx: layout.shadowBlurPx ?? 0,
    shadowOpacity: layout.shadowOpacity ?? 0.5,
    aspectRatio:
      aspect === "9:16" || aspect === "4:3" || aspect === "1:1" || aspect === "16:9"
        ? aspect
        : "16:9",
    cursorVisible: layout.cursorVisible ?? true,
    cursorSizePct: layout.cursorSizePct ?? 150,
  };
}

export function cameraFromLayout(layout: EditLayout): CameraBubbleSettings {
  const shape = layout.webcamShape;
  const size = layout.webcamSize;
  const position = layout.webcamPosition;
  const preset: CameraBubbleSize =
    size === "sm" || size === "lg" || size === "xl" || size === "md" ? size : "md";
  return {
    enabled: layout.webcamEnabled ?? true,
    shape:
      shape === "circle" || shape === "squircle" || shape === "rect_16_9" || shape === "rect"
        ? shape
        : "rect",
    size: preset,
    sizePct: layout.webcamSizePct ?? WEBCAM_SIZE_PRESET_PCT[preset],
    roundnessPct: layout.webcamRoundnessPct ?? 0,
    position:
      position === "top-left" ||
      position === "top-right" ||
      position === "bottom-left" ||
      position === "custom" ||
      position === "bottom-right"
        ? position
        : "bottom-right",
    customX: layout.webcamCustomX ?? 80,
    customY: layout.webcamCustomY ?? 80,
    borderColor: layout.webcamBorderColor ?? "#6366f1",
    borderWidth: layout.webcamBorderWidth ?? 0,
    mirror: layout.webcamMirror ?? true,
    shadow: layout.webcamShadow ?? false,
  };
}

export function layoutFromSettings(
  canvas: CanvasSettings,
  camera: CameraBubbleSettings,
  wallpaperAsset?: string | null,
): EditLayout {
  return {
    aspectRatio: canvas.aspectRatio,
    paddingPx: 0,
    backgroundType: canvas.backgroundType,
    backgroundPreset: canvas.backgroundPreset,
    screenCropLeft: canvas.screenCrop.left,
    screenCropTop: canvas.screenCrop.top,
    screenCropRight: canvas.screenCrop.right,
    screenCropBottom: canvas.screenCrop.bottom,
    screenScalePct: canvas.screenScalePct,
    colorStart: canvas.colorStart,
    colorEnd: canvas.colorEnd,
    cornerRadiusPx: canvas.cornerRadiusPx,
    shadowBlurPx: canvas.shadowBlurPx,
    shadowOpacity: canvas.shadowOpacity,
    wallpaperAsset: wallpaperAsset ?? undefined,
    webcamEnabled: camera.enabled,
    webcamShape: camera.shape,
    webcamSize: camera.size,
    webcamSizePct: camera.sizePct,
    webcamRoundnessPct: camera.roundnessPct,
    webcamPosition: camera.position,
    webcamCustomX: camera.customX,
    webcamCustomY: camera.customY,
    webcamBorderColor: camera.borderColor,
    webcamBorderWidth: camera.borderWidth,
    webcamMirror: camera.mirror,
    webcamShadow: camera.shadow,
    cursorVisible: canvas.cursorVisible,
    cursorSizePct: canvas.cursorSizePct,
  };
}

export interface SilenceConfig {
  thresholdDb: number; // e.g. -38
  minDurationMs: number; // e.g. 400
  paddingMs: number; // e.g. 50
  windowMs?: number;
  stepMs?: number;
  channelPolicy?: string;
}

export interface SilenceBlock {
  id: string;
  startUs: number;
  endUs: number;
  durationMs: number;
  selected: boolean;
  sourceStartUs?: number;
  sourceEndUs?: number;
}

export interface SilenceDetectionResult {
  trackId: string;
  sampleRate: number;
  channels: number;
  channelPolicy: string;
  suggestions: SilenceBlock[];
  diagnostics: string[];
}

// The timeline as tracks of clips (src-tauri/src/sequence)
export type AssetKind = "recording" | "video" | "image" | "audio";
export type StreamKind = "picture" | "sound";
/**
 * What a stream stands for. Pictures: "screen" (the canvas layout, zooms and cursor), "webcam"
 * (the camera bubble) or "overlay" (over the whole canvas). Sound: "mic" (speech: transcribed,
 * captioned, ducks background sound) or "background" (music, game, desktop).
 */
export type Role = "screen" | "webcam" | "overlay" | "mic" | "background";

export interface Stream {
  /** A recording's own track id ("screen", "webcam", "mic", "system"); a file's "picture" or "sound0"... */
  id: string;
  kind: StreamKind;
  role: Role;
  name: string;
  audioPath?: string;
  fps?: number;
}

/** Something that can be played: a recording, a video, an image or audio. */
export interface Asset {
  id: string;
  name: string;
  kind: AssetKind;
  /** Where it is: a recording's folder or the file, used in place. */
  path: string;
  streams: Stream[];
  /** Its length; for an image, how far a clip can be stretched. */
  durationUs: number;
  width: number;
  height: number;
  /** A recording's pauses on its own clock: no media there. */
  pauses?: { startUs: number; endUs: number }[];
  /** The file or folder is no longer there. */
  missing?: boolean;
}

export type TrackKind = "video" | "audio";
/** "contain" fits the whole picture in the canvas; "cover" fills the canvas, cropping it. */
export type Fit = "contain" | "cover";

/** One clip: stream `stream` of asset `asset` from `inUs`, `durationUs` long, at `startUs`. */
export interface Clip {
  id: string;
  asset: string;
  stream: string;
  startUs: number;
  inUs: number;
  durationUs: number;
  /** Clips cut from one moment of an asset share this: they move and trim together. */
  link?: string;
  fit?: Fit;
}

export interface SeqTrack {
  id: string;
  kind: TrackKind;
  /** The user's name; absent shows its number (V1, A2...). */
  name?: string;
  hidden?: boolean;
  muted?: boolean;
  /** Never changed by edits. */
  locked?: boolean;
  /** What its clips stand for; absent: each stream's own role. */
  role?: Role;
  clips: Clip[];
}

export interface Sequence {
  /** Video tracks bottom to top (V1 first), then audio tracks top to bottom (A1 first). */
  tracks: SeqTrack[];
  /** Ripple editing: cuts close up on every track, moves and longer clips make room. */
  magnetic: boolean;
}

export type TrimSide = "previous" | "next";

/** One undoable timeline edit (src-tauri/src/sequence/edit.rs). */
export type SequenceEdit =
  | { kind: "addTrack"; trackKind: TrackKind }
  | { kind: "removeTrack"; trackId: string }
  | { kind: "setTrack"; trackId: string; name: string; hidden: boolean; muted: boolean; locked: boolean; role: Role | null }
  | { kind: "moveTrack"; trackId: string; up: boolean }
  | {
      kind: "placeAsset";
      assetId: string;
      atUs: number;
      trackId?: string | null;
      streams?: string[];
      range?: { startUs: number; endUs: number } | null;
    }
  | { kind: "moveClips"; clipIds: string[]; deltaUs: number; trackId?: string | null; anchorId?: string | null }
  | { kind: "trimClip"; clipId: string; edge: "start" | "end"; toUs: number; ripple?: boolean | null }
  | { kind: "split"; atUs: number; clipIds: string[] }
  | { kind: "delete"; clipIds: string[]; ripple?: boolean | null }
  | { kind: "deleteRange"; ranges: EditedSpan[]; ripple?: boolean | null }
  | { kind: "rippleTrim"; atUs: number; side: TrimSide }
  | { kind: "link"; clipIds: string[] }
  | { kind: "unlink"; clipIds: string[] }
  | { kind: "setMagnetic"; magnetic: boolean }
  | { kind: "setClip"; clipId: string; fit: Fit }
  /** Puts cut time back between the listed clips and the next ones of their source (all, when none). */
  | { kind: "restoreCuts"; clipIds: string[] };

/** The project as the UI sees it (src-tauri/src/project/reader.rs `OpenedProject`). */
export interface OpenedProject {
  projectHandle: string;
  revision: number;
  name: string;
  projectPath?: string;
  /** Where the timeline ends. */
  durationUs: number;
  assets: Asset[];
  sequence: Sequence;
  /** Frames per second the timeline steps by. */
  fps: number;
  diagnostics: string[];
  previewAvailable: boolean;
  undoAvailable: boolean;
  redoAvailable: boolean;
  zooms?: ProjectZoom[];
  dismissedZoomIds?: string[];
  layout?: EditLayout;
  /** Auto webcam layout settings and segments. */
  webcamFocus?: WebcamFocus;
  audio?: AudioSettings;
  captions?: CaptionSettings;
  chapters?: Chapter[];
  shorts?: Short[];
  /** Auto-zoom settings; absent: the defaults. */
  zoomSettings?: ZoomSettings;
  /** Set when this is a short's own timeline: the sequence is the short's. */
  shortView?: string;
}

/** One caption on the timeline's caption track (src-tauri/src/commands/transcript.rs). */
export interface CaptionCueView {
  startUs: number;
  endUs: number;
  text: string;
  wordIds: string[];
  wordStartsUs: number[];
}

export interface CaptionTrackView {
  /** The transcript captions read from; absent until something is transcribed. */
  trackId?: string | null;
  cues: CaptionCueView[];
}

/** A change made on the caption track, saved in the transcript. */
export type CaptionEdit =
  | { kind: "setText"; wordIds: string[]; text: string }
  | { kind: "retime"; wordIds: string[]; startUs: number; endUs: number }
  | { kind: "split"; wordId: string }
  | { kind: "merge"; wordId: string }
  | { kind: "hide"; wordIds: string[]; hidden: boolean };

/** A span of the edited timeline. */
export interface EditedSpan {
  startUs: number;
  endUs: number;
}

// Auto webcam layout (src-tauri/src/webcam_focus.rs)
export interface WebcamFocusSettings {
  speechThresholdDb: number;
  pauseToleranceMs: number;
  /** How long the mouse must rest before the webcam fills the frame, up to 60 s. */
  idleMs: number;
  /** Only fill the frame while the speaker talks. */
  requireSpeech: boolean;
  minFocusMs: number;
  transitionMs: number;
  cursorMovesAreActivity: boolean;
  focusSizePct: number;
}

export interface WebcamFocusSegment {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  source: "auto" | "manual";
  enabled: boolean;
  /** Where the segment lands on the edited timeline. */
  editedRanges?: { startUs: number; endUs: number }[];
}

/** A source range (usually a clip) where the webcam stays in its bubble. */
export interface NormalViewRange {
  sourceStartUs: number;
  sourceEndUs: number;
  /** Filled in by the backend for display; never stored. */
  editedRanges?: EditedRange[];
}

export interface WebcamFocus {
  enabled: boolean;
  /** The recording whose camera the segments are in; absent: the first one. */
  media?: string;
  settings: WebcamFocusSettings;
  segments: WebcamFocusSegment[];
  normalView?: NormalViewRange[];
}

export interface WebcamFocusDetection {
  project: OpenedProject;
  detected: number;
  diagnostics: string[];
}

export const DEFAULT_WEBCAM_FOCUS_SETTINGS: WebcamFocusSettings = {
  speechThresholdDb: -38,
  pauseToleranceMs: 800,
  idleMs: 5000,
  requireSpeech: false,
  minFocusMs: 2500,
  transitionMs: 0,
  cursorMovesAreActivity: true,
  focusSizePct: 100,
};

export const DEFAULT_WEBCAM_FOCUS: WebcamFocus = {
  enabled: false,
  settings: DEFAULT_WEBCAM_FOCUS_SETTINGS,
  segments: [],
};

export type PlaybackState =
  | "closed"
  | "ready"
  | "playing"
  | "paused"
  | "seeking"
  | "ended"
  | "error";

export type ClockKind = "audio" | "monotonic";

export interface PlaybackStatus {
  projectHandle: string;
  state: PlaybackState;
  generation: number;
  positionUs: number;
  durationUs: number;
  clockKind: ClockKind;
  /** The short playing instead of the video, while the Shorts Studio has one in focus. */
  shortId?: string;
  /** How fast it plays: 1 is normal speed. */
  speed?: number;
  previewAvailable: boolean;
  error: string | null;
  diagnostics: string[];
}

export interface EditCut {
  startUs: number;
  endUs: number;
}

export type PreviewHitMode =
  | "consume"
  | "circle"
  | "pass_through"
  | "circle_pass_through"
  | "squircle_pass_through";

export interface PreviewViewport {
  generation: number;
  clip?: [number, number, number, number];
  windowLabel: string;
  x: number;
  y: number;
  width: number;
  height: number;
  backingScale: number;
  visible: boolean;
  occluded: boolean;
  revision: number;
}

export interface PreviewStatus {
  attached: boolean;
  windowLabel: string | null;
  generation: number;
  layoutRevision: number;
  arrangement: string;
  supported: boolean;
  presentedKind: string;
  copiesPerPresent: number;
  copies: number;
  presentedBytes: number;
  backingScale: number;
  physical: { x: number; y: number; width: number; height: number } | null;
  visible: boolean;
  occluded: boolean;
  hitMode: PreviewHitMode;
  /** "native": a macOS child view draws frames. "webview": fetch them with `previewFrame`. */
  surface: "native" | "webview";
  diagnostics: string[];
}

/** How the editor preview is drawn. Export always uses the export settings. */
export interface PreviewQuality {
  /** Shorter side of the preview canvas in pixels (720 = 1280x720 for 16:9); 0 is full size. */
  resolution: number;
  /** Frames drawn per second while playing; 0 follows the source. */
  fps: number;
}

export interface MediaInteropStatus {
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  supported: boolean;
  previewAvailable: boolean;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  colorSpace: string;
  wgpuAdapter: string | null;
  diagnostics: string[];
}

export interface MediaParityReport {
  matched: boolean;
  previewWidth: number;
  previewHeight: number;
  exportWidth: number;
  exportHeight: number;
  previewPtsUs: number;
  exportPtsUs: number;
  maxAbsDelta: number;
  meanAbsDelta: number;
  regionMeanDelta: number;
  compositorMeanDelta: number;
  compositorMaxDelta: number;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  colorSpace: string;
  pcmPeak: number;
  pcmRms: number;
  diagnostics: string[];
}

export type ExportState =
  | "idle"
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export type ExportFailureKind =
  | "collision"
  | "cancelled"
  | "invalid_settings"
  | "source_path"
  | "encoder_busy"
  | "native"
  | "io";

export interface ExportFailure {
  kind: ExportFailureKind;
  message: string;
}

export type ExportQuality = "standard" | "high" | "max";

export interface ExportSettings {
  videoCodec: "h264";
  audioCodec: "aac";
  width: number;
  height: number;
  fps: number;
  destination?: string | null;
  /** Constant-quality preset; ignored when bitrateKbps is set. */
  quality?: ExportQuality;
  /** Average video bitrate; omit to use the quality preset. */
  bitrateKbps?: number | null;
}

export interface ExportStatus {
  jobId: string;
  state: ExportState;
  capturedRevision: number;
  videoCodec: string;
  audioCodec: string;
  width: number;
  height: number;
  fps: number;
  progressNumerator: number;
  progressDenominator: number;
  outputPath: string | null;
  failure: ExportFailure | null;
  diagnostics: string[];
}

export interface SegmentSummary {
  trackId: string;
  relativePath: string;
  startUs: number;
  endUs: number;
  sizeBytes: number;
  mediaTimescale: number;
  mediaStartValue: number;
  hostAnchorUs: number;
  isKeyframeStart: boolean | null;
  available: boolean;
}

export interface SegmentPage {
  segments: SegmentSummary[];
  nextOffset: number | null;
}

// Transcription (src-tauri/src/transcript)
export type TranscriptProvider = "parakeet" | "elevenlabs";

export interface TranscriptSettings {
  provider: TranscriptProvider;
  language: string;
  scribeModel: string;
  keyterms: string[];
  parakeetModelDir: string;
}

export interface TranscriptSettingsView {
  settings: TranscriptSettings;
  elevenlabsKeySource: "keychain" | "file" | "environment" | null;
  parakeetAvailable: boolean;
  parakeetAccelerator: string;
  parakeetModelDir: string;
  parakeetModelPresent: boolean;
}

export interface TranscriptViewWord {
  id: string;
  text: string;
  kind: "word" | "audioEvent";
  sourceStartUs: number;
  sourceEndUs: number;
  confidence?: number;
  speaker?: string;
  /** Null when the word has been cut. */
  editedStartUs: number | null;
  editedEndUs: number | null;
  /** Heard but not shown in the captions. */
  captionHidden?: boolean;
  /** A caption starts at this word. */
  captionBreak?: boolean;
  /** Kept in the caption before it. */
  captionJoin?: boolean;
}

export interface TranscriptView {
  trackId: string;
  provider: TranscriptProvider;
  model: string;
  language: string | null;
  createdAt: string;
  revision: number;
  words: TranscriptViewWord[];
}

export interface TranscriptRunResult {
  view: TranscriptView;
  diagnostics: string[];
}

export interface TranscriptionProgress {
  trackId: string;
  fraction: number;
  message: string;
}

export interface ModelDownloadProgress {
  bytesDone: number;
  bytesTotal: number | null;
}

export interface TranscriptCutSuggestion {
  id: string;
  kind: "filler" | "retake";
  wordIds: string[];
  text: string;
  editedStartUs: number;
  editedEndUs: number;
  /** Rejected in the review list; left out of "remove all". */
  dismissed: boolean;
  /** Found by the built-in rules or by an AI review. */
  source?: "rules" | "ai";
  /** The AI's short explanation. */
  reason?: string;
}

/** A chapter marker, anchored in source time so it survives cuts and reordering. */
export interface Chapter {
  id: string;
  sourceUs: number;
  title: string;
  /** The asset whose time `sourceUs` is in; absent: the first recording. */
  media?: string;
  /** Edited-timeline start, or null when that moment was cut. Filled in by the backend. */
  editedUs?: number | null;
}

export interface ShortLayout {
  cameraPosition: "top" | "bottom";
  /** Share of the frame height the camera takes, 20 to 70. */
  cameraPct: number;
  /** Zoom on the screen part, 0.3 to 3: 1 fills its part, below 1 shows all of it smaller. */
  screenZoom: number;
  followZooms: boolean;
  /** Moves the screen view, -1 to 1 each way, on top of where the zooms point. */
  screenPanX: number;
  screenPanY: number;
  captions: boolean;
  captionSpot: "seam" | "screen" | "camera";
  /** Words per caption in this short; 0 uses the editor's setting. */
  captionMaxWords: number;
  /** Lines a caption may take, 1 to 3; longer ones are drawn smaller. */
  captionLines: number;
  /** Caption size as a percentage of the short's height; 0 uses the editor's. */
  captionSizePct: number;
  /** "project" (the video's own background), "solid", "gradient", "preset" or "wallpaper". */
  backgroundType: "project" | "solid" | "gradient" | "preset" | "wallpaper";
  backgroundColorStart: string;
  backgroundColorEnd: string;
  backgroundPreset: string;
}

/** A vertical clip of the video, anchored in source time at its first and last word. */
export interface Short {
  id: string;
  title: string;
  sourceStartUs: number;
  sourceEndUs: number;
  reason?: string;
  layout: ShortLayout;
  /** The asset whose clock the start and end are on; absent: the first recording. */
  media?: string;
  /** Present once the short was edited on its own; it then no longer follows the video. */
  edit?: unknown;
  /** How long it plays now. */
  lengthUs?: number;
  /** Absent when an end was cut from the video. Filled in by the backend. */
  editedStartUs?: number;
  editedEndUs?: number;
}

export type AiProvider = "openAi" | "openRouter";

export interface AiSettings {
  provider: AiProvider;
  /** Empty uses the default model. */
  openaiModel: string;
  openrouterModel: string;
}

export interface AiSettingsView {
  settings: AiSettings;
  openaiKeySource: "keychain" | "file" | "environment" | null;
  openrouterKeySource: "keychain" | "file" | "environment" | null;
  openaiDefaultModel: string;
  openrouterDefaultModel: string;
}
