export type TrackType = "screen" | "webcam" | "mic" | "system";

export interface TimelineInterval {
  id: string;
  startUs: number;
  endUs: number;
  excluded: boolean;
}

export interface WaveformBucket {
  startUs: number;
  endUs: number;
  peak: number;
  rms: number;
  gap: boolean;
}

export interface WaveformPage {
  trackId: string;
  startUs: number;
  endUs: number;
  sampleRate: number;
  channels: number;
  channelPolicy: string;
  buckets: WaveformBucket[];
  diagnostics: string[];
  cancelled: boolean;
}

export interface Track {
  id: string;
  trackType: TrackType;
  name: string;
  muted: boolean;
  volume: number; // linear gain, 1.0 plays as recorded
  intervals: TimelineInterval[];
  waveform?: WaveformPage;
}

export type ZoomOrigin = "click" | "dwell" | "cluster";

export interface EditedRange {
  startUs: number;
  endUs: number;
}

export interface ZoomConfig {
  generationVersion: number;
  dwellRadiusNorm: number;
  minDwellUs: number;
  clusterRadiusNorm: number;
  clusterGapUs: number;
  rapidClickWindowUs: number;
  minHoldUs: number;
  transitionUs: number;
  maxScale: number;
  clickScale: number;
  dwellScale: number;
  geometryUncertaintyUs: number;
  primaryButtons: number[];
  viewportMargin: number;
}

export interface ZoomSuggestion {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
  transitionUs: number;
  origin: ZoomOrigin;
  contributingEventSeqs: number[];
  editedRanges: EditedRange[];
}

export interface ZoomGeneration {
  version: number;
  config: ZoomConfig;
  suggestions: ZoomSuggestion[];
  diagnostics: string[];
}

export type ZoomSource = "generated" | "manual";

export interface ProjectZoom {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
  transitionUs: number;
  origin: ZoomOrigin;
  contributingEventSeqs: number[];
  source: ZoomSource;
  editedRanges: EditedRange[];
}

export interface ManualZoomInput {
  editedStartUs: number;
  editedEndUs: number;
  centerX: number;
  centerY: number;
  scale: number;
}

export interface ZoomKeyframe {
  id: string;
  zoomId: string;
  tUs: number;
  endUs: number;
  sourceStartUs: number;
  sourceEndUs: number;
  normX: number;
  normY: number;
  scale: number;
  durationMs: number;
  transitionMs: number;
  origin?: ZoomOrigin;
  contributingEventSeqs?: number[];
  source?: ZoomSource;
  pending: boolean;
  isAutoGenerated?: boolean;
}

export type CameraBubbleShape = "rect" | "circle" | "squircle" | "rect_16_9";
export type CameraBubbleSize = "sm" | "md" | "lg" | "xl";
export type CameraBubblePosition = "top-left" | "top-right" | "bottom-left" | "bottom-right" | "custom";

export interface CameraBubbleSettings {
  enabled: boolean;
  shape: CameraBubbleShape;
  size: CameraBubbleSize;
  sizePct: number; // 5 to 60, percent of the canvas short side
  roundnessPct: number; // 0 to 50, rect corner radius as percent of the bubble short side
  position: CameraBubblePosition;
  customX: number;
  customY: number;
  borderColor: string;
  borderWidth: number;
  mirror: boolean;
  shadow: boolean;
}

export type BackgroundPreset = "aurora" | "sunset" | "ocean" | "forest" | "candy" | "graphite";

export interface ScreenCrop {
  left: number; // 0 to 45, percent of the source
  top: number;
  right: number;
  bottom: number;
}

export interface CanvasSettings {
  backgroundType: "gradient" | "solid" | "wallpaper" | "preset";
  backgroundPreset: BackgroundPreset;
  colorStart: string;
  colorEnd: string;
  screenCrop: ScreenCrop;
  screenScalePct: number; // 40 to 100
  cornerRadiusPx: number; // 0 to 32
  shadowBlurPx: number; // 0 to 40
  shadowOpacity: number; // 0.0 to 1.0
  aspectRatio: "16:9" | "9:16" | "4:3" | "1:1";
}

/** Audio polish. Each effect has its own switch and applies to playback and export. */
export interface AudioSettings {
  normalize: boolean;
  /** Integrated loudness target in LUFS, -30 to -8. */
  targetLufs: number;
  noiseReduction: boolean;
  /** How far background noise is lowered, 3 to 30 dB. */
  noiseReductionDb: number;
  duckSystemAudio: boolean;
  /** How far system audio is lowered under speech, 3 to 30 dB. */
  duckDb: number;
  /** Mute and volume per audio track id; tracks without an entry play as recorded. */
  tracks?: Record<string, TrackMix>;
}

export interface TrackMix {
  muted: boolean;
  /** Gain in dB, -30 to +12. */
  volumeDb: number;
}

export const DEFAULT_TRACK_MIX: TrackMix = { muted: false, volumeDb: 0 };
export const TRACK_VOLUME_DB_RANGE = { min: -30, max: 12 } as const;

/** Audio track kinds the mixer plays. */
export function isAudioTrack(trackType: TrackType): boolean {
  return trackType === "mic" || trackType === "system";
}

export const DEFAULT_AUDIO_SETTINGS: AudioSettings = {
  normalize: false,
  targetLufs: -14,
  noiseReduction: false,
  noiseReductionDb: 12,
  duckSystemAudio: false,
  duckDb: 12,
};

/** Captions burned into playback and export from a track's transcript. */
export interface CaptionSettings {
  enabled: boolean;
  /** Transcript to caption; unset picks the microphone, then system audio. */
  trackId?: string;
  position: "bottom" | "middle" | "top";
  /** Distance from the top or bottom edge, 0 to 45 % of the canvas height. */
  offsetPct: number;
  /** Text size, 2 to 15 % of the canvas height. */
  fontSizePct: number;
  textColor: string;
  highlightWords: boolean;
  highlightColor: string;
  outline: boolean;
  background: boolean;
  backgroundColor: string;
  /** 0 to 1. */
  backgroundOpacity: number;
  uppercase: boolean;
  /** Most words on screen at once, 1 to 12. */
  maxWords: number;
}

export const DEFAULT_CAPTION_SETTINGS: CaptionSettings = {
  enabled: false,
  position: "bottom",
  offsetPct: 8,
  fontSizePct: 5.5,
  textColor: "#FFFFFF",
  highlightWords: true,
  highlightColor: "#FACC15",
  outline: true,
  background: false,
  backgroundColor: "#000000",
  backgroundOpacity: 0.55,
  uppercase: false,
  maxWords: 6,
};

export interface EditLayout {
  aspectRatio: string;
  paddingPx: number;
  backgroundType?: string;
  colorStart?: string;
  colorEnd?: string;
  cornerRadiusPx?: number;
  shadowBlurPx?: number;
  shadowOpacity?: number;
  wallpaperAsset?: string | null;
  backgroundPreset?: string;
  screenCropLeft?: number;
  screenCropTop?: number;
  screenCropRight?: number;
  screenCropBottom?: number;
  screenScalePct?: number;
  webcamEnabled?: boolean;
  webcamShape?: string;
  webcamSize?: string;
  webcamSizePct?: number;
  webcamRoundnessPct?: number;
  webcamPosition?: string;
  webcamCustomX?: number;
  webcamCustomY?: number;
  webcamBorderColor?: string;
  webcamBorderWidth?: number;
  webcamMirror?: boolean;
  webcamShadow?: boolean;
}

export const LAYOUT_UNSUPPORTED = {
  rect169: "16:9 webcam crop stays disabled until a dedicated bubble aspect path ships",
} as const;

/// Built-in backgrounds. Mirrors `preset_recipe` in src-tauri/src/render/mod.rs so the
/// swatches look like what preview and export render.
export const BACKGROUND_PRESETS: {
  key: BackgroundPreset;
  label: string;
  base: string;
  blobs: [x: number, y: number, radius: number, color: string][];
}[] = [
  { key: "aurora", label: "Aurora", base: "#0b1026", blobs: [[0.15, 0.2, 0.7, "#3b82f6"], [0.85, 0.3, 0.6, "#a855f7"], [0.5, 1.0, 0.7, "#14b8a6"]] },
  { key: "sunset", label: "Sunset", base: "#1e1033", blobs: [[0.2, 0.9, 0.8, "#f97316"], [0.8, 0.2, 0.7, "#db2777"], [0.55, 0.55, 0.4, "#facc15"]] },
  { key: "ocean", label: "Ocean", base: "#031b34", blobs: [[0.1, 0.1, 0.8, "#0ea5e9"], [0.9, 0.9, 0.8, "#1d4ed8"], [0.6, 0.4, 0.45, "#22d3ee"]] },
  { key: "forest", label: "Forest", base: "#052e16", blobs: [[0.2, 0.8, 0.8, "#15803d"], [0.85, 0.15, 0.6, "#65a30d"], [0.6, 0.6, 0.45, "#0f766e"]] },
  { key: "candy", label: "Candy", base: "#3b0764", blobs: [[0.1, 0.3, 0.7, "#ec4899"], [0.9, 0.7, 0.7, "#8b5cf6"], [0.5, 0.0, 0.5, "#f472b6"]] },
  { key: "graphite", label: "Graphite", base: "#111113", blobs: [[0.2, 0.15, 0.8, "#3f3f46"], [0.85, 0.85, 0.7, "#27272a"], [0.6, 0.4, 0.4, "#52525b"]] },
];

/// CSS approximation of a built-in background for a 16:9 swatch.
export function presetBackgroundCss(key: BackgroundPreset): string {
  const preset = BACKGROUND_PRESETS.find((p) => p.key === key) ?? BACKGROUND_PRESETS[0];
  const layers = preset.blobs.map(
    ([x, y, r, color]) =>
      `radial-gradient(ellipse ${r * 100}% ${r * 178}% at ${x * 100}% ${y * 100}%, ${color}d9, transparent)`,
  );
  return [...layers, preset.base].join(", ");
}

export const WEBCAM_SIZE_PRESET_PCT: Record<CameraBubbleSize, number> = {
  sm: 12.5,
  md: 20,
  lg: 28,
  xl: 36,
};

export function canvasFromLayout(layout: EditLayout): CanvasSettings {
  const aspect = layout.aspectRatio;
  const preset = BACKGROUND_PRESETS.find((p) => p.key === layout.backgroundPreset);
  return {
    backgroundType:
      layout.backgroundType === "solid" ||
      layout.backgroundType === "wallpaper" ||
      layout.backgroundType === "preset"
        ? layout.backgroundType
        : "gradient",
    backgroundPreset: preset?.key ?? "aurora",
    colorStart: layout.colorStart ?? "#312e81",
    colorEnd: layout.colorEnd ?? "#0f172a",
    screenCrop: {
      left: layout.screenCropLeft ?? 0,
      top: layout.screenCropTop ?? 0,
      right: layout.screenCropRight ?? 0,
      bottom: layout.screenCropBottom ?? 0,
    },
    // Canvas padding is gone: screen scale does the same job. Older projects keep their
    // look by folding the padding into the scale (padding is in 1080p-short-side pixels).
    screenScalePct: Math.max(
      1,
      Math.round(
        (layout.screenScalePct ?? 100) * Math.max(0, (1080 - 2 * (layout.paddingPx ?? 0)) / 1080),
      ),
    ),
    cornerRadiusPx: layout.cornerRadiusPx ?? 0,
    shadowBlurPx: layout.shadowBlurPx ?? 0,
    shadowOpacity: layout.shadowOpacity ?? 0.5,
    aspectRatio:
      aspect === "9:16" || aspect === "4:3" || aspect === "1:1" || aspect === "16:9"
        ? aspect
        : "16:9",
  };
}

export function cameraFromLayout(layout: EditLayout): CameraBubbleSettings {
  const shape = layout.webcamShape;
  const size = layout.webcamSize;
  const position = layout.webcamPosition;
  const preset: CameraBubbleSize =
    size === "sm" || size === "lg" || size === "xl" || size === "md" ? size : "md";
  return {
    enabled: layout.webcamEnabled ?? true,
    shape:
      shape === "circle" || shape === "squircle" || shape === "rect_16_9" || shape === "rect"
        ? shape
        : "rect",
    size: preset,
    sizePct: layout.webcamSizePct ?? WEBCAM_SIZE_PRESET_PCT[preset],
    roundnessPct: layout.webcamRoundnessPct ?? 0,
    position:
      position === "top-left" ||
      position === "top-right" ||
      position === "bottom-left" ||
      position === "custom" ||
      position === "bottom-right"
        ? position
        : "bottom-right",
    customX: layout.webcamCustomX ?? 80,
    customY: layout.webcamCustomY ?? 80,
    borderColor: layout.webcamBorderColor ?? "#6366f1",
    borderWidth: layout.webcamBorderWidth ?? 0,
    mirror: layout.webcamMirror ?? true,
    shadow: layout.webcamShadow ?? false,
  };
}

export function layoutFromSettings(
  canvas: CanvasSettings,
  camera: CameraBubbleSettings,
  wallpaperAsset?: string | null,
): EditLayout {
  return {
    aspectRatio: canvas.aspectRatio,
    paddingPx: 0,
    backgroundType: canvas.backgroundType,
    backgroundPreset: canvas.backgroundPreset,
    screenCropLeft: canvas.screenCrop.left,
    screenCropTop: canvas.screenCrop.top,
    screenCropRight: canvas.screenCrop.right,
    screenCropBottom: canvas.screenCrop.bottom,
    screenScalePct: canvas.screenScalePct,
    colorStart: canvas.colorStart,
    colorEnd: canvas.colorEnd,
    cornerRadiusPx: canvas.cornerRadiusPx,
    shadowBlurPx: canvas.shadowBlurPx,
    shadowOpacity: canvas.shadowOpacity,
    wallpaperAsset: wallpaperAsset ?? undefined,
    webcamEnabled: camera.enabled,
    webcamShape: camera.shape,
    webcamSize: camera.size,
    webcamSizePct: camera.sizePct,
    webcamRoundnessPct: camera.roundnessPct,
    webcamPosition: camera.position,
    webcamCustomX: camera.customX,
    webcamCustomY: camera.customY,
    webcamBorderColor: camera.borderColor,
    webcamBorderWidth: camera.borderWidth,
    webcamMirror: camera.mirror,
    webcamShadow: camera.shadow,
  };
}

export interface SilenceConfig {
  thresholdDb: number; // e.g. -38
  minDurationMs: number; // e.g. 400
  paddingMs: number; // e.g. 50
  windowMs?: number;
  stepMs?: number;
  channelPolicy?: string;
}

export interface SilenceBlock {
  id: string;
  startUs: number;
  endUs: number;
  durationMs: number;
  selected: boolean;
  sourceStartUs?: number;
  sourceEndUs?: number;
}

export interface SilenceDetectionResult {
  trackId: string;
  sampleRate: number;
  channels: number;
  channelPolicy: string;
  suggestions: SilenceBlock[];
  diagnostics: string[];
}

export type NativeTrackType = "screen" | "webcam" | "mic_audio" | "system_audio";

export interface NativeTrackDescriptor {
  id: string;
  trackType: NativeTrackType;
  codec: string;
  relativePath: string;
  width?: number;
  height?: number;
  fps?: number;
  sampleRate?: number;
  channels?: number;
  gapsTotal: number;
  mediaTimescale?: number;
}

export interface ProjectManifest {
  version: number;
  sessionId: string;
  projectName: string;
  createdAt: string;
  durationUs: number;
  activeDurationUs: number;
  gapsTotal: number;
  pauseIntervals: { startUs: number; endUs: number }[];
  cursorMode?: string;
  sourceGeometry?: unknown;
  tracks: NativeTrackDescriptor[];
}

export interface TrackSummary {
  descriptor: NativeTrackDescriptor;
  segmentCount: number;
  availableSegmentCount: number;
}

/** One timeline entry in playback order: a range of the recording, or of imported media. */
export interface RetainedInterval {
  startUs: number;
  endUs: number;
  /** Imported media asset id; absent for the recording. */
  media?: string;
}

export type MediaKind = "video" | "image" | "audio";

/** A file imported into the project's media bin (src-tauri/src/media_bin.rs). */
export interface MediaAsset {
  id: string;
  name: string;
  kind: MediaKind;
  relativePath: string;
  audioPath?: string;
  durationUs: number;
  width: number;
  height: number;
}

export interface OpenedProject {
  projectHandle: string;
  revision: number;
  manifest: ProjectManifest;
  sourceDurationUs: number;
  editedDurationUs: number;
  retainedIntervals: RetainedInterval[];
  tracks: TrackSummary[];
  diagnostics: string[];
  previewAvailable: boolean;
  undoAvailable: boolean;
  redoAvailable: boolean;
  zooms?: ProjectZoom[];
  dismissedZoomIds?: string[];
  layout?: EditLayout;
  projectPath?: string;
  /**
   * The recording folder being edited; absent for a project that started empty. For an older
   * recording folder that holds its own edits, the same as `projectPath`.
   */
  recordingPath?: string;
  /** Source ranges the edit cut out that can be restored. */
  removedIntervals?: RetainedInterval[];
  /** Source timestamps where the user split a clip. */
  splitPointsUs?: number[];
  /** Auto webcam layout settings and segments. */
  webcamFocus?: WebcamFocus;
  audio?: AudioSettings;
  captions?: CaptionSettings;
  /** Videos, images and audio imported into the project. */
  mediaAssets?: MediaAsset[];
  chapters?: Chapter[];
  shorts?: Short[];
  /** Video tracks V2, V3, ... above the main sequence, bottom to top. */
  overlayTracks?: OverlayTrack[];
}

// Video tracks above the main sequence (src-tauri/src/tracks.rs)
/** "contain" fits the whole picture in the canvas; "cover" fills the canvas, cropping it. */
export type OverlayFit = "contain" | "cover";

export interface OverlayClip {
  id: string;
  assetId: string;
  /** Where the clip starts on the timeline. */
  startUs: number;
  /** Where in the media the clip starts. */
  inUs: number;
  durationUs: number;
  fit: OverlayFit;
}

export interface OverlayTrack {
  id: string;
  clips: OverlayClip[];
  hidden: boolean;
  muted: boolean;
}

/** One undoable change to the tracks above the main sequence. */
export type TrackEdit =
  | { kind: "addTrack" }
  | { kind: "removeTrack"; trackId: string }
  | { kind: "setTrack"; trackId: string; hidden: boolean; muted: boolean }
  | { kind: "placeMedia"; assetId: string; trackId: string; startUs: number }
  | { kind: "updateClip"; clip: OverlayClip; trackId: string }
  | { kind: "removeClip"; clipId: string }
  | { kind: "liftFromMain"; startUs: number; endUs: number; trackId: string; atUs: number }
  | { kind: "dropToMain"; clipId: string; targetUs: number };

// Auto webcam layout (src-tauri/src/webcam_focus.rs)
export interface WebcamFocusSettings {
  speechThresholdDb: number;
  pauseToleranceMs: number;
  /** How long the mouse must rest before the webcam fills the frame, up to 60 s. */
  idleMs: number;
  /** Only fill the frame while the speaker talks. */
  requireSpeech: boolean;
  minFocusMs: number;
  transitionMs: number;
  cursorMovesAreActivity: boolean;
  focusSizePct: number;
}

export interface WebcamFocusSegment {
  id: string;
  sourceStartUs: number;
  sourceEndUs: number;
  source: "auto" | "manual";
  enabled: boolean;
  /** Where the segment lands on the edited timeline. */
  editedRanges?: { startUs: number; endUs: number }[];
}

/** A source range (usually a clip) where the webcam stays in its bubble. */
export interface NormalViewRange {
  sourceStartUs: number;
  sourceEndUs: number;
  /** Filled in by the backend for display; never stored. */
  editedRanges?: EditedRange[];
}

export interface WebcamFocus {
  enabled: boolean;
  settings: WebcamFocusSettings;
  segments: WebcamFocusSegment[];
  normalView?: NormalViewRange[];
}

export interface WebcamFocusDetection {
  project: OpenedProject;
  detected: number;
  diagnostics: string[];
}

export const DEFAULT_WEBCAM_FOCUS_SETTINGS: WebcamFocusSettings = {
  speechThresholdDb: -38,
  pauseToleranceMs: 800,
  idleMs: 5000,
  requireSpeech: false,
  minFocusMs: 2500,
  transitionMs: 0,
  cursorMovesAreActivity: true,
  focusSizePct: 100,
};

export const DEFAULT_WEBCAM_FOCUS: WebcamFocus = {
  enabled: false,
  settings: DEFAULT_WEBCAM_FOCUS_SETTINGS,
  segments: [],
};

export type PlaybackState =
  | "closed"
  | "ready"
  | "playing"
  | "paused"
  | "seeking"
  | "ended"
  | "error";

export type ClockKind = "audio" | "monotonic";

export interface TrackDecodePlan {
  trackId: string;
  generation: number;
  editedUs: number;
  sourceUs: number | null;
  gap: boolean;
  ended: boolean;
  relativePath: string | null;
  keyframeSourceUs: number | null;
  decodeToSourceUs: number | null;
}

export interface PlaybackStatus {
  projectHandle: string;
  state: PlaybackState;
  generation: number;
  positionUs: number;
  durationUs: number;
  clockKind: ClockKind;
  previewAvailable: boolean;
  openFiles: number;
  plans: TrackDecodePlan[];
  error: string | null;
  diagnostics: string[];
}

export interface EditCut {
  startUs: number;
  endUs: number;
}

export type PreviewHitMode =
  | "consume"
  | "circle"
  | "pass_through"
  | "circle_pass_through"
  | "squircle_pass_through";

export interface PreviewViewport {
  generation: number;
  clip?: [number, number, number, number];
  windowLabel: string;
  x: number;
  y: number;
  width: number;
  height: number;
  backingScale: number;
  visible: boolean;
  occluded: boolean;
  revision: number;
}

export interface PreviewStatus {
  attached: boolean;
  windowLabel: string | null;
  generation: number;
  layoutRevision: number;
  arrangement: string;
  supported: boolean;
  presentedKind: string;
  copiesPerPresent: number;
  copies: number;
  presentedBytes: number;
  backingScale: number;
  physical: { x: number; y: number; width: number; height: number } | null;
  visible: boolean;
  occluded: boolean;
  hitMode: PreviewHitMode;
  /** "native": a macOS child view draws frames. "webview": fetch them with `previewFrame`. */
  surface: "native" | "webview";
  diagnostics: string[];
}

/** How the editor preview is drawn. Export always uses the export settings. */
export interface PreviewQuality {
  /** Shorter side of the preview canvas in pixels (720 = 1280x720 for 16:9); 0 is full size. */
  resolution: number;
  /** Frames drawn per second while playing; 0 follows the source. */
  fps: number;
}

export interface MediaInteropStatus {
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  supported: boolean;
  previewAvailable: boolean;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  colorSpace: string;
  wgpuAdapter: string | null;
  diagnostics: string[];
}

export interface MediaParityReport {
  matched: boolean;
  previewWidth: number;
  previewHeight: number;
  exportWidth: number;
  exportHeight: number;
  previewPtsUs: number;
  exportPtsUs: number;
  maxAbsDelta: number;
  meanAbsDelta: number;
  regionMeanDelta: number;
  compositorMeanDelta: number;
  compositorMaxDelta: number;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  colorSpace: string;
  pcmPeak: number;
  pcmRms: number;
  diagnostics: string[];
}

export type ExportState =
  | "idle"
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export type ExportFailureKind =
  | "collision"
  | "cancelled"
  | "invalid_settings"
  | "source_path"
  | "encoder_busy"
  | "native"
  | "io";

export interface ExportFailure {
  kind: ExportFailureKind;
  message: string;
}

export type ExportQuality = "standard" | "high" | "max";

export interface ExportSettings {
  videoCodec: "h264";
  audioCodec: "aac";
  width: number;
  height: number;
  fps: number;
  destination?: string | null;
  /** Constant-quality preset; ignored when bitrateKbps is set. */
  quality?: ExportQuality;
  /** Average video bitrate; omit to use the quality preset. */
  bitrateKbps?: number | null;
}

export interface ExportStatus {
  jobId: string;
  state: ExportState;
  capturedRevision: number;
  videoCodec: string;
  audioCodec: string;
  width: number;
  height: number;
  fps: number;
  progressNumerator: number;
  progressDenominator: number;
  outputPath: string | null;
  failure: ExportFailure | null;
  diagnostics: string[];
}

export interface SegmentSummary {
  trackId: string;
  relativePath: string;
  startUs: number;
  endUs: number;
  sizeBytes: number;
  mediaTimescale: number;
  mediaStartValue: number;
  hostAnchorUs: number;
  isKeyframeStart: boolean | null;
  available: boolean;
}

export interface SegmentPage {
  segments: SegmentSummary[];
  nextOffset: number | null;
}

export function studioTrackType(trackType: NativeTrackType): TrackType {
  if (trackType === "mic_audio") return "mic";
  if (trackType === "system_audio") return "system";
  return trackType;
}

// Transcription (src-tauri/src/transcript)
export type TranscriptProvider = "parakeet" | "elevenlabs";

export interface TranscriptSettings {
  provider: TranscriptProvider;
  language: string;
  scribeModel: string;
  keyterms: string[];
  parakeetModelDir: string;
}

export interface TranscriptSettingsView {
  settings: TranscriptSettings;
  elevenlabsKeySource: "keychain" | "file" | "environment" | null;
  parakeetAvailable: boolean;
  parakeetAccelerator: string;
  parakeetModelDir: string;
  parakeetModelPresent: boolean;
}

export interface TranscriptViewWord {
  id: string;
  text: string;
  kind: "word" | "audioEvent";
  sourceStartUs: number;
  sourceEndUs: number;
  confidence?: number;
  speaker?: string;
  /** Null when the word has been cut. */
  editedStartUs: number | null;
  editedEndUs: number | null;
}

export interface TranscriptView {
  trackId: string;
  provider: TranscriptProvider;
  model: string;
  language: string | null;
  createdAt: string;
  revision: number;
  words: TranscriptViewWord[];
}

export interface TranscriptRunResult {
  view: TranscriptView;
  diagnostics: string[];
}

export interface TranscriptionProgress {
  trackId: string;
  fraction: number;
  message: string;
}

export interface ModelDownloadProgress {
  bytesDone: number;
  bytesTotal: number | null;
}

export interface TranscriptCutSuggestion {
  id: string;
  kind: "filler" | "retake";
  wordIds: string[];
  text: string;
  editedStartUs: number;
  editedEndUs: number;
  /** Rejected in the review list; left out of "remove all". */
  dismissed: boolean;
  /** Found by the built-in rules or by an AI review. */
  source?: "rules" | "ai";
  /** The AI's short explanation. */
  reason?: string;
}

/** A chapter marker, anchored in source time so it survives cuts and reordering. */
export interface Chapter {
  id: string;
  sourceUs: number;
  title: string;
  /** Edited-timeline start, or null when that moment was cut. Filled in by the backend. */
  editedUs?: number | null;
}

export interface ShortLayout {
  cameraPosition: "top" | "bottom";
  /** Share of the frame height the camera takes, 20 to 70. */
  cameraPct: number;
  /** Extra zoom on the screen part, 1 to 3. */
  screenZoom: number;
  followZooms: boolean;
  captions: boolean;
  captionSpot: "seam" | "screen" | "camera";
}

/** A vertical clip of the video, anchored in source time at its first and last word. */
export interface Short {
  id: string;
  title: string;
  sourceStartUs: number;
  sourceEndUs: number;
  reason?: string;
  layout: ShortLayout;
  /** Absent when an end was cut from the video. Filled in by the backend. */
  editedStartUs?: number;
  editedEndUs?: number;
}

export type AiProvider = "openAi" | "openRouter";

export interface AiSettings {
  provider: AiProvider;
  /** Empty uses the default model. */
  openaiModel: string;
  openrouterModel: string;
}

export interface AiSettingsView {
  settings: AiSettings;
  openaiKeySource: "keychain" | "file" | "environment" | null;
  openrouterKeySource: "keychain" | "file" | "environment" | null;
  openaiDefaultModel: string;
  openrouterDefaultModel: string;
}
